[project]
name = "nerfst0"
version = "0.0.1"

dependencies = [
    "nerfstudio"
]

[tool.setuptools.packages.find]
include = ["nerfst*"]

[project.entry-points.'nerfstudio.method_configs']
nerfst = 'nerfst.nerfst_config:nerfst_method'